### ISSUE TITLE
Frontend refinements

### ISSUE THREAD

**Issue by mgdesign** [sparkfabrik/company-playbook#193]
### TODO

- [x] Add styling to the block-quotes
- [x] Check spacing between headers and text (see attached image)
- [x] Improve the styling of the inline code, now is low contrast and hard to read
- [x] investigate the possibility to add syntax highlight to code blocks using a library, or eventually add a more contrasted style to them (grey on black with monospace font)

As stretch goals:
- [x] Add a "copy to clipboard" action button on the playbook code blocks

cc @stickgrinder if you need to add any other items to the list, please do

[SF_playbook_headers](https://github.com/sparkfabrik/company-playbook/assets/5602741/047917e2-6bc3-4ab3-8da7-cb5bc5f811eb)
